services:
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: nginx_lab
    ports:
      - "80:80"
      - "443:443"

  app1:
    build:
      context: app1
      dockerfile: DockerfileHorrible
    container_name: app1_lab

  app2:
    build:
      context: app2
      dockerfile: DockerfileHorrible
    container_name: app2_lab