services:
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: nginx_lab
    network_mode: "host"

  app1:
    build:
      context: app1
      dockerfile: Dockerfile
    container_name: app1_lab
    network_mode: "host"
    environment:
      SECRET_PASS: "my_password"

  app2:
    build:
      context: app2
      dockerfile: Dockerfile
    container_name: app2_lab
    network_mode: "host"
    volumes:
      - "/:/host:rw"