name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - CI/CD

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        run: |
          cd app1
          docker build -t jubastik/itmo-ops-labs:latest .
          docker push jubastik/itmo-ops-labs:latest
