name: Build and Push Docker Image

on:
  push:
    branches:
      - CI/CD

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 20

    steps:
      - name: Bitwarden secrets
        uses: bitwarden/sm-action@v2
        with:
          access_token: ${{ secrets.BW_ACCESS_TOKEN }}
          base_url: https://vault.bitwarden.com
          secrets: |
            c7ba33b0-14d6-4aae-9c06-b20f010dab86 > DOCKERHUB_USERNAME
            7998fe1d-dcc5-4613-ac5d-b20f010cb5ed > DOCKERHUB_TOKEN


      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and push
        run: |
          cd app1
          docker build -t jubastik/itmo-ops-labs:ci_cd .
          docker push jubastik/itmo-ops-labs:ci_cd
