name: Security Checks

on:
  push:
    branches:
      - main
      - CI/CD
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install safety

      - name: Check vulnerabilities
        run: |
          safety check -i 70612 --full-report